#!/bin/bash
#report pairing times for each type of parameter
for p in a d159 d201 d224 e f
do
    echo -en $p'\t'
    test/benchmark < param/$p.param | awk '/time =/ {printf "%s", $5 "\t" } /prepro/ {print $6}'
done
