#!/bin/bash -ex

if [ `which libtoolize` != '' ]; then
    LT=libtoolize
elif [ `which glibtoolize` != '' ]; then
    LT=glibtoolize
else
    exit 1
fi
$LT --force --copy
aclocal
autoheader
automake --add-missing --copy --gnu
autoconf

if test -f config.status; then
    sh config.status
fi
