#!/usr/bin/gawk -f
# Extract GMP-style documentation from source using AsciiDoc format.
# Fragile, e.g. requires function definition/declaration
# to end with ")\n" or ");" or ") {"
# and does not play well with function pointer parameters
/^\/\*@/ {
    outfile = "gen/" gensub(".*manual ", "", 1) ".txt"
    print "Writing to " outfile
    n = 0
    getline
    while ($0 != "*/") {
	a[n] = $0
	n++
	getline
    }

#    do {
#	getline
#	print
#    } while (!match($0, ";") && !match($0, "{"))
    getline
    sub("static inline ", "")
    s = gensub("(\\w*)\\(", " *\\1*(", 1)  # Function name.
    s = gensub("\\((.*$)", "('\\1", 1, s)  # First parameter.
    gsub(", *", "', '", s)  # Separating commas.
    gsub("_ptr", "_t", s)
    while (!match(s, ");") && !match(s, ") *$") && !match(s, ") *{")) {
	getline
	gsub("^ *", "")      # Remove leading whitespace.
	gsub(", *", "', '")  # Commas again.
	gsub("_ptr", "_t")
	s = s $0             # Concatenate.
    }
    s = gensub("(.*)\\)", "\\1')", 1, s)  # Last parameter
    gsub("_ptr", "_t", s)
    gsub(")[^)]*$", ")", s);
    print s "\n" > outfile
    if (n > 0) {
      print "____" > outfile
      for(i = 0; i < n; i++) {
	  print a[i] > outfile
      }
      print "____" > outfile
    }
}
